name: tests

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: json, mbstring
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-stable --no-interaction --no-progress

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Check code style
        run: vendor/bin/pint --test
